print('Level 1')
print('#1')
empty_tp = tuple()
print(empty_tp)
print('#2')
family = ('Drake', 'Pac', 'Mercy', 'Polo')
print(family)
print('#3')
family = list(family)
family.append('AR')
family.append('Jony')
family = tuple(family)
print(family)
print('#4')
print('Number of family: ', len(family))
print('#5')
family = list(family)
family.append('West')
family.append('Cole')
family = tuple(family)
family_members = family
print(family_members)
print('\nLevel 2')
print('#1')
del family_members
print('#2')
fruits = ('Watermelon', 'Mango', 'Apple', 'Orange')
vegetables = ('leek', 'cress', 'chives', 'lettuce')
animal = ('Monkey', 'dog', 'cat', 'bird')
food_stuff_tp = fruits + vegetables + animal
print(food_stuff_tp)
print('#3')
food_stuff_lt = list(food_stuff_tp)
print(food_stuff_lt)
print('#4')
mid_lt = food_stuff_lt[1:3]
mid_tp = food_stuff_tp[1:3]
print('middle of list: ', mid_lt)
print('middle of tuple: ', mid_tp)
print('#5')
print('First three items: ', food_stuff_lt[0:3])
print('Last three items: ', food_stuff_lt[-4:-1])
print('#6')
del food_stuff_tp
print('#7')
nordic_countries = ('Denmark', 'Finland','Iceland', 'Norway', 'Sweden')
print('Estonia' in nordic_countries)
print('Iceland' in nordic_countries)
